### ISSUE TITLE
Additional run instructions

### ISSUE THREAD

**Issue by kcwhite** [enesacikoglu/BitbucketRepoCloner#1]
It might be helpful to add instructions on how to launch the service locally since not all of us are overly familiar with Spring.

mvn spring-boot:run

Also, you may wish to point out that repos will be cloned to a sub-folder with the same name as the BitBucket project - I explicitly added the project name to the localRepoDirectory because I didn't know that.  An example might be helpful.

**Comment by enesacikoglu** [comment]
Hello @kcwhite,

Thanks for your PR.

Sorry for late response,I missed ur PR.

I will change and add required instructers asap.

Regards

Enes

**Comment by enesacikoglu** [comment]
Done.
